packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  workerd: true
  sharp: false
  koffi: false
  node-pty: false
  '@mongodb-js/zstd': false
  node-liblzma: false
  protobufjs: false
  '@google/genai': false

minimumReleaseAge: 0

patchedDependencies:
  '@deepseek-ai/dsh-llm@0.2.0-rc.2': patches/@deepseek-ai__dsh-llm@0.2.0-rc.2.patch
