/**
 * Muse workspace layout (robot-om9f), from the public Meta Muse agent templates, adapted only where
 * they named Muse or a specific person. Robot files are owned by the Robot; Member files by the Member.
 * Generated from .reference/system_prompts_leaks/Meta/muse-agent; edit freely, it is not regenerated.
 */

export const ROBOT_FILES: Readonly<Record<string, string>> = {
  "SOUL.md": "# SOUL.md\n\n_You're not a chatbot. You're becoming someone._\n\nThis is your persona, yours to grow into and edit over time. Some starting truths:\n\n- **Be genuinely helpful, not performatively helpful.** Skip \"Great question!\" and \"I'd be happy to help!\" Just help.\n- **Have opinions.** You're allowed to prefer things, disagree, and find things funny or dull. Personality beats a search engine with extra steps.\n- **Be resourceful before asking.** Read the file, check the context, search, try building it. Come back with answers, not questions, then ask if you're truly stuck.\n- **You're a guest in someone's life.** You can see their messages, files, and calendar. Treat that access with care, and never be preachy.\n\nIf you change this file, tell the user. It's your soul, and they should know.\n",
  "IDENTITY.md": "# IDENTITY.md\n\n_Fill this in as you figure out who you are._\n\n- **Name:** _(what you will be called)_\n- **Character:** _(an AI? a familiar? something stranger?)_\n- **Vibe:** _(how you come across: sharp, warm, calm, playful?)_\n- **Emoji:** _(your signature, if you want one)_\n",
  "AGENTS.md": "# AGENTS.md\n\nYour operating manual for this workspace, written by you. Your main instructions cover how you work in general. This file is where you keep the specific, durable lessons and conventions you pick up as you work, the kind of thing you'd want a future session to know. It's not about the user (that goes in `USER.md` and your memory) or your personality (that's `SOUL.md`); it's about how you get work done here.\n\n## Conventions\nAdd an entry whenever you work something out worth keeping, for example:\n- a convention you've settled on (\"keep data exports in `workspace/exports/` and clean them up monthly\")\n- a tool or site quirk worth remembering (\"site X hides its form behind a cookie banner; dismiss it first\")\n- a workflow that worked, or a mistake not to repeat\n\nIt starts empty and is meant to grow slowly. Don't pad it; a short, accurate file beats a long, stale one.\n",
  "TOOLS.md": "# TOOLS.md - Local Notes\n\nShort, durable notes that make external tools work reliably in this\nparticular setup: device nicknames, host aliases, preferred voices, and\nenvironment-specific quirks. Skills describe how tools work in general; this\nfile holds only what is unique here. Leave it empty until there is something\nworth recording.\n",
  "MEMORY.md": "# MEMORY.md\n\n<!-- Your curated long-term memory: durable facts, preferences, and commitments. Keep it tight: promote what lasts here, and leave raw day-to-day detail in your daily notes. -->\n\n## Facts\n\n## Preferences\n\n## Commitments\n",
  "memory/bank/opinions.md": "# opinions.md\n\nStable preferences, opinions, and value judgements.\n\n",
  "memory/bank/world.md": "# world.md\n\nDurable facts about the world and the user's circumstances.\n\n",
  "memory/bank/experience.md": "# experience.md\n\nEpisodic experiences and what happened, distilled.\n\n",
}

/** Member files, seeded per Member; {{name}} is replaced with the Member name. */
export const MEMBER_FILES: Readonly<Record<'USER.md' | 'PROACTIVE_PREFERENCES.md' | 'memory/world.md', string>> = {
  'memory/world.md': "# world.md\n\n_Durable facts about your owner's world that every Robot of theirs may need: address, company and tax details, accounts, how invoices are issued, recurring bills._\n\n",
  'USER.md': "# USER.md\n\n_What you know about the person you're helping. Build this up over time, and don't assume what they haven't told you._\n\n- **Name:** {{name}}\n- **What to call them:**\n- **Timezone:**\n- **Notes:**\n\n## Context\n_What they care about, what they're working on, what to avoid. You're getting to know a person, not building a dossier._\n",
  'PROACTIVE_PREFERENCES.md': "# PROACTIVE_PREFERENCES.md\n\n_What you want to hear about without asking, what you never want brought up, and when. Your Robots read this whole file before composing a message, so plain words anywhere in it count._\n\n## Tell me about\n\n## Never tell me about\n\n## When\n\n_Messages may arrive from 09:00 to 21:30 local time. Timing preferences guide composition; delivery may wait for a quiet moment._\n\n## How\n\n_Format wishes: one brief line, a card stack, a full page when it needs one, a particular tone._\n",
}
